version: '3'

services:
  payroll-front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: payroll-front-end
    container_name: payroll-front-end
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm run start:server"

networks:
    app-network:
      driver: bridge
