version: '3.7'

services:
  backend-deel:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-deel
    container_name: backend-deel
    ports:
      - "3001:3001"
    depends_on:
      - cache
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm start"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  dbdata6:
    driver: local

networks:
    app-network:
      driver: bridge
