version: '3.7'

services:
  deel-back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: deel-back-end
    container_name: deel-back-end
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: >
      sh -c "npm start"

networks:
    app-network:
      driver: bridge
